package com.bhargav.blog.blog_api.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Data
@Entity
public class Comment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private int postId; // Reference to the associated post
    private String content;
    private String author;

    @CreationTimestamp
    private LocalDateTime createdAt;

    // Constructors, getters, and setters can be generated by Lombok
}
